### ISSUE TITLE
Absolute path on windows

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/glob#4]
Hello, 
I have this behavior on Windows with Glob 1.1.0 and I want to understand if this is me doing something wrong.

```dart
import 'dart:io';
import 'package:glob/glob.dart';

main() {
  new File('c:/myfolder/a.txt').createSync(recursive: true);

  String pattern = r'c:/myfolder/**';
  print(new Glob(pattern).listSync().length);
  print(new Glob(pattern, caseSensitive: false).listSync().length);
  print(new Glob(pattern, caseSensitive: true).listSync().length);
}
```

It prints:
0
0
1

Why is `caseSensitive: true` necessary here? 
Is it normal to have more result with caseSensitive: `true` than `false`?

**Comment by nex3** [comment]
This definitely looks like a bug. Unfortunately, I don't have a Windows machine easily accessible to debug it, so I'll need your help. Can you clone this package locally and have it print out the parameters it's passing to `Directory.listSync()`?

**Comment by xavierhainaux** [comment]
I tried quickly to debug and the difference seems to be: 
with `caseSensitive: false`, the getter `_ListTreeNode._isIntermediate` always returns false.

I can print for you the parameters you want. For Directory.listSync in ListTree it passes
`c:/` 
and in _ListTreeNode, if _isIntermediate is true, it prints:
`c:/myfolder`

**Comment by nex3** [comment]
> I tried quickly to debug and the difference seems to be: 
> with `caseSensitive: false`, the getter `_ListTreeNode._isIntermediate` always returns false.

This is expected. If the glob is case-insensitive, we need to manually list every directory to see which matching filenames are there.

> I can print for you the parameters you want. For Directory.listSync in ListTree it passes
> `c:/` 
> and in _ListTreeNode, if _isIntermediate is true, it prints:
> `c:/myfolder`

This also looks reasonable so far. Can you include *all* the `Directory.listSync` arguments as well as the return values?

**Comment by xavierhainaux** [comment]
Hello, sorry for the delay.
I added some prints in list_tree.dart line 388.
Like that:
```dart
    print(dir);
    return new Directory(dir).listSync(followLinks: followLinks)
        .expand((entity) {
      print('Entity: $entity');
      var entities = [];
      var basename = entity.path.substring(dir.length + 1);
      print('Basename: $basename');
```

and I have
```
c:/
Entity: Directory: 'c:/myfolder'
Basename: yfolder
Entity: Directory: 'c:/Program Files'
Basename: rogram Files
Entity: Directory: 'c:/Program Files (x86)'
Basename: rogram Files (x86)
Entity: Directory: 'c:/Windows'
Basename: indows
```

It seems the basename is off by one.
