### ISSUE TITLE
Deprecated syntax in README

### ISSUE THREAD

**Issue by silverhairs** [dart-lang/glob#49]
The methods **list()** and **listSync()** of the Glob class seem to be replaced by **listFileSystem()** and **listFileSystemSync()** but the example used in the readme still uses the old methods.

**Comment by GeekVisit** [comment]
I don't see where this was fixed ? Readme is still referencing old syntax.

**Comment by GeekVisit** [comment]
I see that I just had to import import 'package:glob/list_local_fs.dart';  and listSync() becomes available.   But I think the documentation still needs to reflect ? At least the install page on pub.dev to reflect the import. I couldn't figure out a way to submit a pull request for the pub.dev page.
