### ISSUE TITLE
Six tests are failing on Windows

### ISSUE THREAD

**Issue by whesse** [dart-lang/glob#5]
The test test/test_list.dart has 6 subtests failing on Windows.  The failures can be seen at
 https://build.chromium.org/p/client.dart.packages/builders/packages-windows-glob/

**Comment by nex3** [comment]
I need to get a Windows laptop at some point to debug other issues, so I'll look into this then.

**Comment by nex3** [comment]
I only see two failures when I run this locally: list()/listSync() reports exceptions for non-existent directories.
